version: 2
project_name: rtelegram

builds:
  - id: default
    binary: rtelegram
    main: .
    goos: [windows, darwin, linux]
    goarch: [amd64, arm64, "386"]
    ignore:
      - goos: darwin
        goarch: "386"
    env:
      - CGO_ENABLED=0
      - GOWORK=off
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    formats: ["zip"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  header: |
    {{ .TagBody }}

changelog:
  use: git
